//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Library.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.CreateUserSoap")]
    public interface CreateUserSoap {
        
        // CODEGEN: Generating message contract since element name GeneratePassResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GeneratePass", ReplyAction="*")]
        Library.ServiceReference1.GeneratePassResponse GeneratePass(Library.ServiceReference1.GeneratePassRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GeneratePass", ReplyAction="*")]
        System.Threading.Tasks.Task<Library.ServiceReference1.GeneratePassResponse> GeneratePassAsync(Library.ServiceReference1.GeneratePassRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GeneratePassRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GeneratePass", Namespace="http://tempuri.org/", Order=0)]
        public Library.ServiceReference1.GeneratePassRequestBody Body;
        
        public GeneratePassRequest() {
        }
        
        public GeneratePassRequest(Library.ServiceReference1.GeneratePassRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GeneratePassRequestBody {
        
        public GeneratePassRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GeneratePassResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GeneratePassResponse", Namespace="http://tempuri.org/", Order=0)]
        public Library.ServiceReference1.GeneratePassResponseBody Body;
        
        public GeneratePassResponse() {
        }
        
        public GeneratePassResponse(Library.ServiceReference1.GeneratePassResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GeneratePassResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GeneratePassResult;
        
        public GeneratePassResponseBody() {
        }
        
        public GeneratePassResponseBody(string GeneratePassResult) {
            this.GeneratePassResult = GeneratePassResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface CreateUserSoapChannel : Library.ServiceReference1.CreateUserSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CreateUserSoapClient : System.ServiceModel.ClientBase<Library.ServiceReference1.CreateUserSoap>, Library.ServiceReference1.CreateUserSoap {
        
        public CreateUserSoapClient() {
        }
        
        public CreateUserSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CreateUserSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CreateUserSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CreateUserSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Library.ServiceReference1.GeneratePassResponse Library.ServiceReference1.CreateUserSoap.GeneratePass(Library.ServiceReference1.GeneratePassRequest request) {
            return base.Channel.GeneratePass(request);
        }
        
        public string GeneratePass() {
            Library.ServiceReference1.GeneratePassRequest inValue = new Library.ServiceReference1.GeneratePassRequest();
            inValue.Body = new Library.ServiceReference1.GeneratePassRequestBody();
            Library.ServiceReference1.GeneratePassResponse retVal = ((Library.ServiceReference1.CreateUserSoap)(this)).GeneratePass(inValue);
            return retVal.Body.GeneratePassResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Library.ServiceReference1.GeneratePassResponse> Library.ServiceReference1.CreateUserSoap.GeneratePassAsync(Library.ServiceReference1.GeneratePassRequest request) {
            return base.Channel.GeneratePassAsync(request);
        }
        
        public System.Threading.Tasks.Task<Library.ServiceReference1.GeneratePassResponse> GeneratePassAsync() {
            Library.ServiceReference1.GeneratePassRequest inValue = new Library.ServiceReference1.GeneratePassRequest();
            inValue.Body = new Library.ServiceReference1.GeneratePassRequestBody();
            return ((Library.ServiceReference1.CreateUserSoap)(this)).GeneratePassAsync(inValue);
        }
    }
}
